development:
  host: localhost
  port: 3306
  database: empmng_development
  user: root
  password:

test:
  host: localhost
  port: 3306
  database: test_db
  user: root
  password:

production:
  host: localhost
  port: 3306
  database: production_db
  user: root
  password:
